/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litl_leveldb_DB */

#ifndef _Included_com_litl_leveldb_DB
#define _Included_com_litl_leveldb_DB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_litl_leveldb_DB_nativeOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_DB_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativePut
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_DB_nativePut
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeGet
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_litl_leveldb_DB_nativeGet
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeDelete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_DB_nativeDelete
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeWrite
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_DB_nativeWrite
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeDestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_DB_nativeDestroy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeIterator
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_litl_leveldb_DB_nativeIterator
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeGetSnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_litl_leveldb_DB_nativeGetSnapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_DB
 * Method:    nativeReleaseSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_DB_nativeReleaseSnapshot
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
