/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litl_leveldb_WriteBatch */

#ifndef _Included_com_litl_leveldb_WriteBatch
#define _Included_com_litl_leveldb_WriteBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_litl_leveldb_WriteBatch
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_litl_leveldb_WriteBatch_nativeCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_litl_leveldb_WriteBatch
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_WriteBatch_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_WriteBatch
 * Method:    nativeDelete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_WriteBatch_nativeDelete
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_litl_leveldb_WriteBatch
 * Method:    nativePut
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_WriteBatch_nativePut
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_litl_leveldb_WriteBatch
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_WriteBatch_nativeClear
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
