/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litl_leveldb_Iteration */

#ifndef _Included_com_litl_leveldb_Iteration
#define _Included_com_litl_leveldb_Iteration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_Iteration_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeSeekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_Iteration_nativeSeekToFirst
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeSeekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_Iteration_nativeSeekToLast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeSeek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_Iteration_nativeSeek
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_litl_leveldb_Iteration_nativeValid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeNext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_Iteration_nativeNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativePrev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litl_leveldb_Iteration_nativePrev
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_litl_leveldb_Iteration_nativeKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litl_leveldb_Iteration
 * Method:    nativeValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_litl_leveldb_Iteration_nativeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
